import { useState } from 'react'
import { deleteWithReferencePolicy, findReferences } from '../../compiler/referenceResolver'
import { useEditorStore } from '../../store/editorStore'

export function EntityEditor() {
  const { currentProject: project, updateDraft, updateProject } = useEditorStore()
  const [selectedId, setSelectedId] = useState<string | null>(project?.draft.entities[0]?.id ?? null)
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null)
  if (!project) return null
  const selected = project.draft.entities.find((entity) => entity.id === selectedId)
  const add = () => updateDraft((draft) => { const id = `person-new-${draft.entities.length + 1}`; draft.entities.push({ id, type: 'person', name: '新人物', summary: '', description: '', aliases: [], tags: [] }); setSelectedId(id) }, 'entity-add')
  const remove = (policy: 'block' | 'remove') => { if (!deleteTarget) return; const result = deleteWithReferencePolicy(project.draft, deleteTarget, policy); if (result.ok) updateProject((next) => { next.draft = result.draft }, 'entity-delete'); setDeleteTarget(null); setSelectedId(null) }
  return <section className="editor-document split-editor"><header><div><span>ENTITY REGISTER</span><h1>人物与实体</h1></div><button className="primary-button" onClick={add}>新建人物</button></header><div className="master-detail"><div className="master-list" role="listbox" aria-label="实体列表">{project.draft.entities.map((entity) => <button role="option" aria-selected={selectedId === entity.id} className={selectedId === entity.id ? 'selected' : ''} key={entity.id} onClick={() => { setSelectedId(entity.id); updateProject((next) => { next.uiState.selectedEntityId = entity.id }, 'selection') }}><strong>{entity.name}</strong><small>{entity.type} · {entity.id}</small></button>)}</div>{selected ? <div className="detail-form"><div className="stable-id"><label>稳定ID<input value={selected.id} readOnly /></label><span>{findReferences(project.draft, selected.id).length} 个引用</span></div><label>显示名称<input value={selected.name} onChange={(event) => updateDraft((draft) => { const entity = draft.entities.find((item) => item.id === selected.id); if (entity) entity.name = event.target.value }, `entity.${selected.id}.name`)} /></label><label>类型<select value={selected.type} onChange={(event) => updateDraft((draft) => { const entity = draft.entities.find((item) => item.id === selected.id); if (entity) entity.type = event.target.value as typeof entity.type }, `entity.${selected.id}.type`)}><option value="person">人物</option><option value="location">地点</option><option value="organization">组织</option><option value="device">设备</option><option value="custom">自定义</option></select></label><label>摘要<input value={selected.summary} onChange={(event) => updateDraft((draft) => { const entity = draft.entities.find((item) => item.id === selected.id); if (entity) entity.summary = event.target.value }, `entity.${selected.id}.summary`)} /></label><label>说明<textarea value={selected.description} onChange={(event) => updateDraft((draft) => { const entity = draft.entities.find((item) => item.id === selected.id); if (entity) entity.description = event.target.value }, `entity.${selected.id}.description`)} /></label><button className="text-danger" onClick={() => setDeleteTarget(selected.id)}>删除实体</button></div> : <div className="editor-empty">选择实体查看属性，或创建一条新记录。</div>}</div>
    {deleteTarget && <div className="inline-dialog" role="dialog" aria-modal="true"><h2>删除实体？</h2><p>发现 {findReferences(project.draft, deleteTarget).length} 个引用。被引用实体不能静默删除。</p><div><button onClick={() => setDeleteTarget(null)}>取消</button><button disabled={findReferences(project.draft, deleteTarget).length > 0} onClick={() => remove('block')}>安全删除</button><button className="danger-button" onClick={() => remove('remove')}>删除并移除引用</button></div></div>}
  </section>
}

