import { useEditorStore } from '../../store/editorStore'

export function DesktopEditor() {
  const project = useEditorStore((state) => state.currentProject)
  const updateDraft = useEditorStore((state) => state.updateDraft)
  if (!project) return null
  return <section className="editor-document desktop-author"><header><div><span>DESKTOP COMPOSER</span><h1>桌面布局</h1><p>拖动的键盘替代是下方X/Y坐标。预览采用1440×900安全区域。</p></div><div><button>1280×720</button><button className="selected">1440×900</button></div></header><div className="desktop-composer"><div className="desktop-preview" style={{ '--draft-theme': project.draft.desktop.themeColor } as React.CSSProperties}><div className="desktop-preview-top">{project.draft.desktop.systemName} <span>{project.draft.desktop.lastLoginMessage}</span></div>{project.draft.applications.filter((app) => app.enabled).map((app) => <button key={app.id} style={{ left: `${Math.min(app.desktopX / 4, 300)}px`, top: `${Math.min(app.desktopY / 4, 160)}px` }}><i>{app.title.slice(0, 1)}</i><span>{app.title}</span></button>)}<footer>ARCHIVE/OS · AUTHOR PREVIEW</footer></div><aside><h2>系统外观</h2><label>系统名称<input value={project.draft.desktop.systemName ?? ''} onChange={(event) => updateDraft((draft) => { draft.desktop.systemName = event.target.value }, 'desktop.systemName')} /></label><label>启动文案<input value={project.draft.desktop.bootMessage ?? ''} onChange={(event) => updateDraft((draft) => { draft.desktop.bootMessage = event.target.value }, 'desktop.bootMessage')} /></label><label>主题色<input type="color" value={project.draft.desktop.themeColor ?? '#557b78'} onChange={(event) => updateDraft((draft) => { draft.desktop.themeColor = event.target.value }, 'desktop.themeColor')} /></label><h2>图标坐标</h2>{project.draft.applications.filter((app) => app.enabled).map((app) => <fieldset key={app.id}><legend>{app.title}</legend><label>X<input type="number" value={app.desktopX} onChange={(event) => updateDraft((draft) => { const item = draft.applications.find((candidate) => candidate.id === app.id); if (item) item.desktopX = Number(event.target.value) }, `app.${app.id}.x`)} /></label><label>Y<input type="number" value={app.desktopY} onChange={(event) => updateDraft((draft) => { const item = draft.applications.find((candidate) => candidate.id === app.id); if (item) item.desktopY = Number(event.target.value) }, `app.${app.id}.y`)} /></label></fieldset>)}</aside></div></section>
}

