import { useState } from 'react'
import { useEditorStore } from '../../store/editorStore'

export function MessengerEditor() {
  const project = useEditorStore((state) => state.currentProject)
  const updateDraft = useEditorStore((state) => state.updateDraft)
  const [threadId, setThreadId] = useState(project?.draft.chats[0]?.id ?? null)
  if (!project) return null
  const thread = project.draft.chats.find((item) => item.id === threadId)
  return <section className="editor-document"><header><div><span>MESSAGE AUTHORING</span><h1>讯息</h1><p>联系人、消息时间和附件均保存为声明式数据。</p></div><button className="primary-button" onClick={() => updateDraft((draft) => { const id = `thread-${draft.chats.length + 1}`; draft.chats.push({ id, title: '新联系人', messages: [] }); setThreadId(id) }, 'chat-add')}>新建联系人</button></header><div className="messenger-author"><aside>{project.draft.chats.map((item) => <button key={item.id} className={threadId === item.id ? 'selected' : ''} onClick={() => setThreadId(item.id)}><strong>{item.title}</strong><small>{item.messages.length} 条消息</small></button>)}</aside>{thread ? <div className="message-author-main"><label>联系人名称<input value={thread.title} onChange={(event) => updateDraft((draft) => { const item = draft.chats.find((candidate) => candidate.id === thread.id); if (item) item.title = event.target.value }, `chat.${thread.id}.title`)} /></label><div className="message-timeline">{thread.messages.map((message, index) => <article key={message.id}><div><input aria-label={`消息 ${index + 1} 发送者`} value={message.sender} onChange={(event) => updateDraft((draft) => { draft.chats.find((item) => item.id === thread.id)!.messages[index]!.sender = event.target.value }, `message.${message.id}.sender`)} /><input aria-label={`消息 ${index + 1} 时间`} value={message.time} onChange={(event) => updateDraft((draft) => { draft.chats.find((item) => item.id === thread.id)!.messages[index]!.time = event.target.value }, `message.${message.id}.time`)} /></div><textarea aria-label={`消息 ${index + 1} 内容`} value={message.text} onChange={(event) => updateDraft((draft) => { draft.chats.find((item) => item.id === thread.id)!.messages[index]!.text = event.target.value }, `message.${message.id}.text`)} /></article>)}</div><button onClick={() => updateDraft((draft) => { const item = draft.chats.find((candidate) => candidate.id === thread.id); item?.messages.push({ id: `message-${Date.now()}`, sender: project.draft.subject.name ?? '电脑主人', time: '12:00', text: '新消息' }) }, 'message-add')}>添加消息</button></div> : <div className="editor-empty">新建或选择联系人。</div>}</div></section>
}

