import { useState } from 'react'
import { useEditorStore } from '../../store/editorStore'

export function FileSystemEditor() {
  const project = useEditorStore((state) => state.currentProject)
  const updateDraft = useEditorStore((state) => state.updateDraft)
  const [selectedId, setSelectedId] = useState<string | null>(project?.draft.files[0]?.id ?? null)
  if (!project) return null
  const selected = project.draft.files.find((file) => file.id === selectedId)
  const addFolder = () => updateDraft((draft) => { draft.folders.push({ id: `folder-${draft.folders.length + 1}`, name: '新文件夹' }) }, 'folder-add')
  const addFile = () => updateDraft((draft) => { const id = `file-text-${draft.files.length + 1}`; draft.files.push({ id, name: '新文本文件.txt', folder: draft.folders[0]?.name ?? '桌面', content: '' }); setSelectedId(id) }, 'file-add')
  return <section className="editor-document split-editor"><header><div><span>VIRTUAL FILE SYSTEM</span><h1>文件系统</h1><p>编辑虚构文件树、文本内容和声明式解锁规则。</p></div><div><button onClick={addFolder}>新建文件夹</button><button className="primary-button" onClick={addFile}>新建文本文件</button></div></header><div className="file-author-grid"><aside><h2>目录</h2><button className="selected">桌面</button>{project.draft.folders.map((folder) => <button key={folder.id}>{folder.name}</button>)}</aside><div className="file-author-list"><div className="file-list-head"><span>名称</span><span>目录</span><span>状态</span></div>{project.draft.files.map((file) => <button key={file.id} className={selectedId === file.id ? 'selected' : ''} onClick={() => setSelectedId(file.id)}><strong>{file.name}</strong><span>{file.folder}</span><small>{file.locked ? '已锁定' : '普通文件'}</small></button>)}</div>{selected ? <div className="detail-form"><label>稳定ID<input value={selected.id} readOnly /></label><label>文件名<input value={selected.name} onChange={(event) => updateDraft((draft) => { const file = draft.files.find((item) => item.id === selected.id); if (file) file.name = event.target.value }, `file.${selected.id}.name`)} /></label><label>所在目录<select value={selected.folder} onChange={(event) => updateDraft((draft) => { const file = draft.files.find((item) => item.id === selected.id); if (file) file.folder = event.target.value }, `file.${selected.id}.folder`)}><option>桌面</option>{project.draft.folders.map((folder) => <option key={folder.id}>{folder.name}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={Boolean(selected.locked)} onChange={(event) => updateDraft((draft) => { const file = draft.files.find((item) => item.id === selected.id); if (file) file.locked = event.target.checked }, `file.${selected.id}.locked`)} />需要密码解锁</label>{selected.locked && <label>密码<input value={selected.password ?? ''} onChange={(event) => updateDraft((draft) => { const file = draft.files.find((item) => item.id === selected.id); if (file) file.password = event.target.value }, `file.${selected.id}.password`)} /><small>不要在谜题正文中直接暴露密码。</small></label>}<label>纯文本内容<textarea rows={12} value={selected.content} onChange={(event) => updateDraft((draft) => { const file = draft.files.find((item) => item.id === selected.id); if (file) file.content = event.target.value }, `file.${selected.id}.content`)} /></label></div> : <div className="editor-empty">选择一个文件进行编辑。</div>}</div></section>
}

