import { ArchiveDialog } from '../../features/system/ArchiveDialog'
import type { CommunityCaseDetail, CommunityCaseVersion } from '../types/communityTypes'
import type { DownloadProgress } from '../client/downloadCasePackage'
import type { PreparedCommunityInstall } from '../install/communityInstallManager'

export type InstallPhase = 'confirm' | 'downloading' | 'validating' | 'ready' | 'installing' | 'success' | 'error'
export function InstallProgressDialog({ detail, version, phase, progress, prepared, error, onClose, onDownload, onInstall, onCancel, onStart, onMuseum }: { detail: CommunityCaseDetail; version: CommunityCaseVersion; phase: InstallPhase; progress: DownloadProgress | null; prepared: PreparedCommunityInstall | null; error: string | null; onClose: () => void; onDownload: () => void; onInstall: () => void; onCancel: () => void; onStart: () => void; onMuseum: () => void }) {
  const actions = phase === 'confirm' ? <><button onClick={onClose}>取消</button><button className="primary-button" onClick={onDownload}>下载并验证</button></> : phase === 'downloading' ? <button onClick={onCancel}>取消下载</button> : phase === 'ready' ? <><button onClick={onClose}>稍后安装</button><button className="primary-button" onClick={onInstall}>安装到档案馆</button></> : phase === 'success' ? <><button onClick={onClose}>关闭</button><button onClick={onMuseum}>查看我的档案</button><button className="primary-button" onClick={onStart}>开始调查</button></> : phase === 'error' ? <><button onClick={onClose}>关闭</button><button className="primary-button" onClick={onDownload}>重试</button></> : <button disabled>处理中…</button>
  return <ArchiveDialog title={phase === 'success' ? '安装成功' : `安装到档案馆 · ${detail.title}`} onClose={phase === 'downloading' || phase === 'installing' ? onCancel : onClose} actions={actions}><div className="install-dialog" aria-live="polite"><dl><div><dt>版本</dt><dd>{version.version}</dd></div><div><dt>发布者</dt><dd>{detail.publisherId}</dd></div><div><dt>包大小</dt><dd>{(version.packageByteSize / 1024).toFixed(1)} KB</dd></div><div><dt>引擎要求</dt><dd>≥ {version.engineCompatibility.minimum}</dd></div><div><dt>许可证</dt><dd>{version.license.name}</dd></div></dl>{detail.contentWarnings.length > 0 && <p className="community-warning">内容提示：{detail.contentWarnings.join('、')}</p>}{phase === 'confirm' && <><p>自动校验状态：已通过社区技术校验；{detail.curated ? '维护者已进行人工精选。' : '尚未人工审阅。'}</p><p>确认后才会下载完整案件包。下载完成后仍需 SHA-256 和本地安全校验。</p></>}{phase === 'downloading' && <div className="install-progress"><strong>正在下载</strong><progress max={progress?.totalBytes ?? undefined} value={progress?.downloadedBytes} /> <span>{progress?.percent === null ? `${progress.downloadedBytes} bytes` : `${progress?.percent ?? 0}%`}</span></div>}{phase === 'validating' && <p>正在计算 SHA-256，并检查包格式、资源、引用与可达性…</p>}{phase === 'ready' && prepared && <><p className="validation-pass">✓ SHA-256 匹配 · 完整案件安全校验通过</p><dl><div><dt>文件</dt><dd>{prepared.imported.assets.size + 3}</dd></div><div><dt>资源</dt><dd>{prepared.imported.caseDefinition.assets.length}</dd></div><div><dt>线索</dt><dd>{prepared.imported.caseDefinition.clues.length}</dd></div><div><dt>应用</dt><dd>{prepared.imported.caseDefinition.applications.length}</dd></div></dl><p>案件尚未写入。请再次确认“安装到档案馆”。</p></>}{phase === 'installing' && <p>正在事务式写入案件、资源与来源记录…</p>}{phase === 'success' && <p className="validation-pass">案件已安装。未自动创建调查进度，也未自动开始案件。</p>}{phase === 'error' && <p className="community-error" role="alert">{error}</p>}</div></ArchiveDialog>
}
