import { useState } from 'react'
import { useEditorStore } from '../../store/editorStore'

export function MailEditor() {
  const project = useEditorStore((state) => state.currentProject)
  const updateDraft = useEditorStore((state) => state.updateDraft)
  const [selectedId, setSelectedId] = useState(project?.draft.emails[0]?.id ?? null)
  if (!project) return null
  const selected = project.draft.emails.find((mail) => mail.id === selectedId)
  const add = (folder: '收件箱' | '草稿') => updateDraft((draft) => { const id = `email-${folder === '草稿' ? 'draft' : 'inbox'}-${draft.emails.length + 1}`; draft.emails.push({ id, folder, from: folder === '草稿' ? draft.subject.name ?? '电脑主人' : '发件人', subject: '新邮件', time: '12:00', body: '' }); setSelectedId(id) }, 'mail-add')
  return <section className="editor-document"><header><div><span>MAIL AUTHORING</span><h1>邮件</h1><p>正文仅支持纯文本或安全Markdown；HTML和远程内容会被校验拒绝。</p></div><div><button onClick={() => add('收件箱')}>添加收件邮件</button><button className="primary-button" onClick={() => add('草稿')}>添加草稿</button></div></header><div className="mail-author"><aside><button className="selected">全部邮件 <span>{project.draft.emails.length}</span></button><button>收件箱 <span>{project.draft.emails.filter((item) => item.folder === '收件箱').length}</span></button><button>草稿 <span>{project.draft.emails.filter((item) => item.folder === '草稿').length}</span></button></aside><div className="mail-author-list">{project.draft.emails.map((mail) => <button key={mail.id} className={mail.id === selectedId ? 'selected' : ''} onClick={() => setSelectedId(mail.id)}><strong>{mail.subject}</strong><span>{mail.from}</span><small>{mail.folder} · {mail.time}</small></button>)}</div>{selected ? <div className="detail-form"><label>邮件ID<input value={selected.id} readOnly /></label><label>文件夹<select value={selected.folder} onChange={(event) => updateDraft((draft) => { const mail = draft.emails.find((item) => item.id === selected.id); if (mail) mail.folder = event.target.value as typeof mail.folder }, `mail.${selected.id}.folder`)}><option>收件箱</option><option>草稿</option></select></label><label>发件人<input value={selected.from} onChange={(event) => updateDraft((draft) => { const mail = draft.emails.find((item) => item.id === selected.id); if (mail) mail.from = event.target.value }, `mail.${selected.id}.from`)} /></label><label>主题<input value={selected.subject} onChange={(event) => updateDraft((draft) => { const mail = draft.emails.find((item) => item.id === selected.id); if (mail) mail.subject = event.target.value }, `mail.${selected.id}.subject`)} /></label><label>时间<input value={selected.time} onChange={(event) => updateDraft((draft) => { const mail = draft.emails.find((item) => item.id === selected.id); if (mail) mail.time = event.target.value }, `mail.${selected.id}.time`)} /></label><label>正文<textarea rows={12} value={selected.body} onChange={(event) => updateDraft((draft) => { const mail = draft.emails.find((item) => item.id === selected.id); if (mail) mail.body = event.target.value }, `mail.${selected.id}.body`)} /></label></div> : <div className="editor-empty">选择邮件查看正文。</div>}</div></section>
}
