import { expect, test, type Page } from '@playwright/test'
import { resolve } from 'node:path'

function watchRuntime(page: Page) {
  const errors: string[] = []
  const failedResources: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  page.on('response', (response) => { if (response.status() >= 400) failedResources.push(`${response.status()} ${response.url()}`) })
  return { errors, failedResources }
}

async function enterWorkshop(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: '档案工坊' }).click()
  await expect(page.getByRole('heading', { name: '档案工坊' })).toBeVisible()
}

async function createTemplateProject(page: Page, title = '消失的备用钥匙') {
  await page.getByRole('button', { name: /创建案件工程|创建第一个工程/ }).first().click()
  await page.getByRole('radio', { name: '最小可玩模板' }).check()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('案件名称').fill(title)
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '创建并打开' }).click()
  await expect(page.getByText('PROJECT OVERVIEW')).toBeVisible()
}

test('captures the complete Archive Workshop visual acceptance set', async ({ page }) => {
  const runtime = watchRuntime(page)
  await enterWorkshop(page)
  await page.screenshot({ path: 'docs/images/stage4-workshop-home.png', fullPage: true })
  await page.getByRole('button', { name: /创建案件工程|创建第一个工程/ }).first().click()
  await page.screenshot({ path: 'docs/images/stage4-create-project.png', fullPage: true })
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '创建并打开' }).click()
  await expect(page.getByText('PROJECT OVERVIEW')).toBeVisible()
  await page.screenshot({ path: 'docs/images/stage4-editor-overview.png', fullPage: true })

  await page.getByRole('button', { name: '人物与实体' }).click()
  await expect(page.getByRole('heading', { name: '人物与实体' })).toBeVisible()
  await page.screenshot({ path: 'docs/images/stage4-entity-editor.png', fullPage: true })
  await page.getByRole('button', { name: '桌面布局' }).click()
  await page.screenshot({ path: 'docs/images/stage4-desktop-editor.png', fullPage: true })
  await page.getByRole('button', { name: '文件系统' }).click()
  await page.screenshot({ path: 'docs/images/stage4-file-tree-editor.png', fullPage: true })
  await page.getByRole('button', { name: '线索与条件' }).click()
  await page.screenshot({ path: 'docs/images/stage4-clue-builder.png', fullPage: true })
  await page.getByRole('button', { name: '添加AND组' }).click()
  await page.screenshot({ path: 'docs/images/stage4-condition-builder.png', fullPage: true })
  await page.getByRole('button', { name: '剧情触发器' }).click()
  await page.screenshot({ path: 'docs/images/stage4-trigger-editor.png', fullPage: true })
  await page.getByRole('button', { name: '最终推理' }).click()
  await page.screenshot({ path: 'docs/images/stage4-deduction-editor.png', fullPage: true })
  await page.getByRole('button', { name: '资源管理器' }).click()
  await expect(page.getByText('spare-key-cover.png')).toBeVisible()
  await page.screenshot({ path: 'docs/images/stage4-asset-manager.png', fullPage: true })
  await page.getByRole('button', { name: '校验结果' }).click()
  await page.getByRole('button', { name: '运行完整校验' }).click()
  await expect(page.getByText('校验通过')).toBeVisible()
  await page.screenshot({ path: 'docs/images/stage4-validation-center.png', fullPage: true })
  await page.getByRole('button', { name: '试玩' }).click()
  await expect(page.getByText('试玩模式 / PREVIEW SESSION')).toBeVisible()
  const skip = page.getByRole('button', { name: '跳过介绍' })
  if (await skip.count()) await skip.click()
  await page.screenshot({ path: 'docs/images/stage4-live-preview.png', fullPage: true })
  await page.getByRole('button', { name: '返回档案工坊' }).click()
  await page.getByRole('button', { name: '导出' }).click()
  await expect(page.getByRole('dialog', { name: '导出案件' })).toBeVisible()
  await page.screenshot({ path: 'docs/images/stage4-publish-flow.png', fullPage: true })
  expect(runtime.errors).toEqual([])
  expect(runtime.failedResources).toEqual([])
})

test('template edit, autosave, reload, undo, snapshot restore and publish round trip', async ({ page }) => {
  const runtime = watchRuntime(page)
  await enterWorkshop(page)
  await createTemplateProject(page)
  await page.getByRole('button', { name: '基本信息' }).click()
  const title = page.getByLabel('案件标题')
  await title.fill('备用钥匙：修订版')
  await expect(page.getByText('已保存')).toBeVisible({ timeout: 5_000 })
  await page.getByRole('button', { name: '人物与实体' }).click()
  await page.getByRole('option', { name: /周岚/ }).click()
  const name = page.getByLabel('显示名称')
  await name.fill('周岚·测试')
  await page.getByRole('button', { name: '快照' }).click()
  await page.getByRole('button', { name: '创建当前快照' }).click()
  await expect(page.getByText('手动创建')).toBeVisible()
  await page.getByRole('button', { name: '关闭快照' }).click()
  await name.fill('周岚·第二版')
  await page.getByRole('button', { name: '撤销' }).click()
  await expect(name).toHaveValue('周岚')
  await page.getByRole('button', { name: '重做' }).click()
  await expect(name).toHaveValue('周岚·第二版')
  await page.getByRole('button', { name: '快照' }).click()
  await page.locator('.snapshot-list article').filter({ hasText: '手动创建' }).getByRole('button', { name: '恢复' }).click()
  await page.getByRole('button', { name: '确认恢复' }).click()
  await page.getByRole('button', { name: '关闭快照' }).click()
  await expect(name).toHaveValue('周岚·测试')
  await page.reload()
  await page.getByRole('button', { name: '档案工坊' }).click()
  await page.getByRole('button', { name: '打开' }).click()
  await page.getByRole('button', { name: '基本信息' }).click()
  await expect(page.getByLabel('案件标题')).toHaveValue('备用钥匙：修订版')
  await page.getByRole('button', { name: '校验结果' }).click()
  await page.getByRole('button', { name: '运行完整校验' }).click()
  await expect(page.getByText('校验通过')).toBeVisible()
  await page.getByRole('button', { name: '导出' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出.ldmcase' }).click()
  expect((await download).suggestedFilename()).toMatch(/\.ldmcase$/)
  await expect(page.getByText(/已生成并往返校验/)).toBeVisible()
  expect(runtime.errors).toEqual([])
})

test('blank project reports actionable errors and project import/export stays distinct', async ({ page }) => {
  await enterWorkshop(page)
  await page.getByRole('button', { name: /创建案件工程|创建第一个工程/ }).first().click()
  await page.getByRole('radio', { name: '空白工程' }).check()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByLabel('工程名称').fill('空白校验工程')
  await page.getByLabel('caseId').fill('case-empty-validation')
  await page.getByLabel('案件名称').fill('尚未完成的案件')
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '创建并打开' }).click()
  await page.getByRole('button', { name: '校验结果' }).click()
  await page.getByRole('button', { name: '运行完整校验' }).click()
  await expect(page.getByText('已阻止')).toBeVisible()
  await expect(page.locator('.issue-table button').first()).toBeVisible()
  await page.getByRole('button', { name: '工程列表' }).click()
  const projectDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出备份' }).click()
  expect((await projectDownload).suggestedFilename()).toMatch(/\.ldmproject$/)
})

test('preview state is isolated and an exported case installs as a playable archive', async ({ page }) => {
  const runtime = watchRuntime(page)
  await enterWorkshop(page)
  await createTemplateProject(page, '可安装的备用钥匙')
  await page.getByRole('button', { name: '试玩' }).click()
  await expect(page.getByText('试玩模式 / PREVIEW SESSION')).toBeVisible()
  const skip = page.getByRole('button', { name: '跳过介绍' })
  if (await skip.count()) await skip.click()
  await page.getByRole('button', { name: '返回档案工坊' }).click()
  const formalKeys = await page.evaluate(() => Object.keys(localStorage).filter((key) => key.startsWith('archive-os:case:case-spare-key')))
  expect(formalKeys).toEqual([])
  await page.getByRole('button', { name: '档案馆', exact: true }).click()
  const packagePath = resolve(process.cwd(), 'release-assets/minimal-valid-case.ldmcase')
  await page.locator('input[type=file][accept*=".ldmcase"]').setInputFiles(packagePath)
  await expect(page.getByText(/已安装案件：消失的备用钥匙/)).toBeVisible()
  await expect(page.getByRole('heading', { name: '消失的备用钥匙' })).toBeVisible()
  await page.getByRole('button', { name: '查看 消失的备用钥匙 案件简介' }).click()
  await expect(page.getByText('周岚', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '开始调查' }).click()
  await page.getByRole('button', { name: '跳过启动' }).click()
  await page.getByRole('button', { name: '恢复上次会话' }).click()
  const onboarding = page.getByRole('button', { name: '跳过介绍' })
  if (await onboarding.count()) await onboarding.click()
  await expect(page.getByTestId('desktop')).toBeVisible()
  expect(runtime.errors).toEqual([])
})

test('workshop stays usable at 1280x720 and with reduced motion', async ({ page }) => {
  const runtime = watchRuntime(page)
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await enterWorkshop(page)
  await createTemplateProject(page)
  await page.getByRole('button', { name: '线索与条件' }).click()
  await expect(page.getByRole('heading', { name: '线索与条件' })).toBeVisible()
  const canvas = page.locator('.editor-canvas')
  const box = await canvas.boundingBox()
  expect(box?.width).toBeGreaterThan(500)
  expect(box?.height).toBeGreaterThan(500)
  expect(runtime.errors).toEqual([])
  expect(runtime.failedResources).toEqual([])
})

test('global search locates a file and a second tab defaults to read-only', async ({ page, context }) => {
  const runtime = watchRuntime(page)
  await enterWorkshop(page)
  await createTemplateProject(page)
  await page.keyboard.press('Control+K')
  await page.getByPlaceholder('ID、文件、人物、线索或正文').fill('备用钥匙仍在')
  await page.getByRole('option', { name: /钥匙交接\.txt/ }).click()
  await expect(page.getByRole('heading', { name: '文件系统' })).toBeVisible()
  await expect(page.getByLabel('文件名')).toHaveValue('钥匙交接.txt')

  const second = await context.newPage()
  await second.goto('/')
  await second.getByRole('button', { name: '档案工坊' }).click()
  await second.getByRole('button', { name: '打开' }).click()
  await expect(second.getByRole('dialog', { name: '该工程正在另一个标签中编辑' })).toBeVisible()
  await second.getByRole('button', { name: '只读打开' }).click()
  await expect(second.getByText(/只读模式/)).toBeVisible()
  await expect(second.getByRole('button', { name: '立即保存' })).toBeDisabled()
  expect(runtime.errors).toEqual([])
})
