import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

function watchErrors(page: Page) {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  return errors
}

async function startCase(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: '查看案件简介' }).click()
  await page.getByRole('button', { name: '开始调查' }).click()
  await page.getByRole('button', { name: '跳过启动' }).click()
  await page.getByRole('button', { name: '恢复上次会话' }).click()
  const onboarding = page.getByRole('button', { name: '跳过介绍' })
  if (await onboarding.count()) await onboarding.click()
  await expect(page.getByTestId('desktop')).toBeVisible()
}

async function openApp(page: Page, name: string) {
  await page.getByRole('button', { name, exact: true }).dblclick()
  await expect(page.getByRole('dialog', { name })).toBeVisible()
}

async function closeApp(page: Page, name: string) {
  await page.getByRole('button', { name: `关闭 ${name}` }).click()
}

async function discoverFirstSix(page: Page) {
  await openApp(page, '邮件')
  await page.getByRole('button', { name: /HX217 订单取消成功/ }).click()
  await closeApp(page, '邮件')
  await openApp(page, '讯息')
  await page.getByRole('button', { name: /周屿 · 23:12/ }).click()
  await closeApp(page, '讯息')
  await openApp(page, '照片')
  await page.getByRole('button', { name: /IMG_1117_发给唐遥/ }).click()
  await page.getByRole('button', { name: '查看元数据' }).click()
  await closeApp(page, '照片')
  await openApp(page, '浏览记录')
  await page.getByRole('button', { name: /如何保留照片画面但更改拍摄时间/ }).click()
  await closeApp(page, '浏览记录')
  await openApp(page, '回收站')
  await page.getByRole('button', { name: /告别信_v3/ }).click()
  await closeApp(page, '回收站')
  await openApp(page, '日历')
  await page.getByRole('button', { name: '林然生日' }).click()
  await closeApp(page, '日历')
}

async function discoverAllTwelve(page: Page) {
  await discoverFirstSix(page)
  await openApp(page, '系统日志')
  await page.getByRole('button', { name: /创建隐藏用户 LINRAN/ }).click()
  await page.getByRole('button', { name: /HOME-NET-5G/ }).click()
  await closeApp(page, '系统日志')
  await openApp(page, '邮件')
  await page.getByRole('button', { name: /草稿/ }).click()
  await page.getByRole('button', { name: /给妈妈/ }).click()
  await page.getByRole('button', { name: /收件箱/ }).click()
  await page.getByRole('button', { name: /北岸酒店预订成功/ }).click()
  await closeApp(page, '邮件')
  await openApp(page, '讯息')
  await page.getByRole('button', { name: /房东陈女士/ }).click()
  await page.getByRole('button', { name: /陈女士 · 23:31/ }).click()
  await closeApp(page, '讯息')
  await openApp(page, '我的文件')
  await page.getByRole('button', { name: /不要打开/ }).click()
  await page.getByRole('button', { name: /mirror\.lock/ }).dblclick()
  await page.getByRole('textbox', { name: 'mirror.lock 密码' }).fill('1119')
  await page.getByRole('button', { name: '解锁' }).click()
  await expect(page.getByText(/mirror\.lock 已解锁/)).toBeVisible()
  await page.getByRole('button', { name: /录音/ }).click()
  await page.getByRole('button', { name: /录音_2316/ }).dblclick()
  await page.getByRole('button', { name: '辅助转写' }).click()
  await closeApp(page, '我的文件')
  await expect(page.getByRole('button', { name: /已记录 12 \/ 12/ })).toBeVisible()
}

test('museum, case detail and distinct application screenshots render without errors', async ({ page }) => {
  const errors = watchErrors(page)
  await page.goto('/')
  await page.screenshot({ path: 'docs/images/stage2-museum-home.png', fullPage: true })
  await page.getByRole('button', { name: '查看案件简介' }).click()
  await page.screenshot({ path: 'docs/images/stage2-case-detail.png', fullPage: true })
  await page.getByRole('button', { name: '开始调查' }).click()
  await page.getByRole('button', { name: '跳过启动' }).click()
  await page.getByRole('button', { name: '恢复上次会话' }).click()
  await page.getByRole('button', { name: '跳过介绍' }).click()
  await page.screenshot({ path: 'docs/images/stage2-desktop.png', fullPage: true })
  await openApp(page, '我的文件')
  await page.screenshot({ path: 'docs/images/stage2-file-explorer.png', fullPage: true })
  for (const viewport of [{ width: 1366, height: 768 }, { width: 1280, height: 720 }]) {
    await page.setViewportSize(viewport)
    const box = await page.getByRole('dialog', { name: '我的文件' }).boundingBox()
    expect(box?.x).toBeGreaterThanOrEqual(0)
    expect(box?.y).toBeGreaterThanOrEqual(0)
    expect((box?.x ?? 0) + (box?.width ?? 0)).toBeLessThanOrEqual(viewport.width)
    expect((box?.y ?? 0) + (box?.height ?? 0)).toBeLessThanOrEqual(viewport.height)
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await closeApp(page, '我的文件')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu', { name: 'A/OS 系统菜单' })).toBeVisible()
  await page.screenshot({ path: 'docs/images/stage2-system-menu.png', fullPage: true })
  expect(errors).toEqual([])
})

test('exit and continue preserves C01 and the open mail window', async ({ page }) => {
  const errors = watchErrors(page)
  await startCase(page)
  await openApp(page, '邮件')
  await page.getByRole('button', { name: /HX217 订单取消成功/ }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('menuitem', { name: /保存并返回档案馆/ }).click()
  await expect(page.getByText('1 / 12')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: '继续调查' }).click()
  await expect(page.getByTestId('desktop')).toBeVisible()
  await expect(page.getByRole('dialog', { name: '邮件' })).toBeVisible()
  await expect(page.getByRole('button', { name: /已记录 1 \/ 12/ })).toBeVisible()
  const save = await page.evaluate(() => JSON.parse(localStorage.getItem('archive-os:case-001') ?? '{}'))
  expect(save.discoveredClueIds).toContain('C01')
  expect(errors).toEqual([])
})

test('restart confirmation cancels safely, then clears case progress but keeps sound settings', async ({ page }) => {
  const errors = watchErrors(page)
  await startCase(page)
  await openApp(page, '设置')
  await page.getByRole('checkbox', { name: /系统音效/ }).uncheck()
  await closeApp(page, '设置')
  await openApp(page, '邮件')
  await page.getByRole('button', { name: /HX217 订单取消成功/ }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('menuitem', { name: /保存并返回档案馆/ }).click()
  await page.getByRole('button', { name: '重新调查' }).click()
  await expect(page.getByRole('dialog', { name: '重新开始调查？' })).toBeVisible()
  await page.getByRole('button', { name: '取消' }).click()
  await expect(page.getByText('1 / 12')).toBeVisible()
  await page.getByRole('button', { name: '重新调查' }).click()
  await page.getByRole('button', { name: '清除进度并重新开始' }).click()
  await expect(page.getByText('0 / 12')).toBeVisible()
  await expect.poll(async () => page.evaluate(() => JSON.parse(localStorage.getItem('archive-os:case-001') ?? '{}'))).toMatchObject({ discoveredClueIds: [], settings: { sound: false } })
  expect(errors).toEqual([])
})

test('window move, resize, minimize, restore and maximize survive save and resume', async ({ page }) => {
  const errors = watchErrors(page)
  await startCase(page)
  await openApp(page, '我的文件')
  const window = page.getByRole('dialog', { name: '我的文件' })
  const titlebar = window.locator('.window-titlebar')
  const titleBox = await titlebar.boundingBox()
  if (!titleBox) throw new Error('File window titlebar was not measurable')
  await page.mouse.move(titleBox.x + 180, titleBox.y + 15)
  await page.mouse.down()
  await page.mouse.move(titleBox.x + 260, titleBox.y + 65, { steps: 4 })
  await page.mouse.up()
  const resize = window.locator('.resize-se')
  const resizeBox = await resize.boundingBox()
  if (!resizeBox) throw new Error('File window resize handle was not measurable')
  await page.mouse.move(resizeBox.x + 2, resizeBox.y + 2)
  await page.mouse.down()
  await page.mouse.move(resizeBox.x + 72, resizeBox.y + 52, { steps: 4 })
  await page.mouse.up()
  const movedBox = await window.boundingBox()
  await page.getByRole('button', { name: '最小化 我的文件', exact: true }).click()
  await expect(window).toBeHidden()
  await page.getByRole('button', { name: '恢复 我的文件' }).click()
  await expect(window).toBeVisible()
  await page.getByRole('button', { name: '最大化 我的文件' }).click()
  await expect(page.getByRole('button', { name: '还原 我的文件' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('menuitem', { name: /保存并返回档案馆/ }).click()
  await page.getByRole('button', { name: '继续调查' }).click()
  await expect(page.getByRole('dialog', { name: '我的文件' })).toBeVisible()
  await expect(page.getByRole('button', { name: '还原 我的文件' })).toBeVisible()
  await titlebar.dblclick()
  const restoredBox = await window.boundingBox()
  expect(Math.abs((restoredBox?.width ?? 0) - (movedBox?.width ?? 0))).toBeLessThan(8)
  expect(errors).toEqual([])
})

test('all 12 clues, password 1119, evidence relation and final deduction remain reachable', async ({ page }) => {
  const errors = watchErrors(page)
  await startCase(page)
  await discoverAllTwelve(page)
  await expect.poll(async () => page.evaluate(() => JSON.parse(localStorage.getItem('archive-os:case-001') ?? '{}').discoveredClueIds?.length ?? 0)).toBe(12)
  const save = await page.evaluate(() => JSON.parse(localStorage.getItem('archive-os:case-001') ?? '{}'))
  expect(save.discoveredClueIds).toEqual(expect.arrayContaining(Array.from({ length: 12 }, (_, index) => `C${String(index + 1).padStart(2, '0')}`)))
  expect(save.unlockedItemIds).toContain('identity-draft')
  await openApp(page, '证据板')
  for (const id of ['C01', 'C02', 'C03', 'C05', 'C08', 'C09']) await page.getByRole('button', { name: `标记 ${id} 为关键证据` }).click()
  await page.getByLabel('关系起点').selectOption('C01')
  await page.getByLabel('关系终点').selectOption('C02')
  await page.getByRole('button', { name: '连接' }).click()
  await page.screenshot({ path: 'docs/images/stage2-evidence-board.png', fullPage: true })
  await page.getByRole('button', { name: '打开最终推理' }).click()
  await page.getByLabel('主动制造已经离开的假象').check()
  await page.getByLabel('周屿的住所').check()
  await page.getByLabel('周屿准备使用的新身份').check()
  await page.getByLabel('个人推理（只保存在本地）').fill('航班取消与旧照片证明周屿制造了出发假象，住所网络的新身份登录显示他仍在本地。')
  await page.getByRole('button', { name: '提交推理' }).click()
  await expect(page.locator('.result-screen')).toContainText('档案重建完成')
  await expect(page.getByRole('button', { name: '保存并返回档案馆' })).toBeVisible()
  expect(errors).toEqual([])
})

test('mail and photo metadata screenshots show distinct application structures', async ({ page }) => {
  const errors = watchErrors(page)
  await startCase(page)
  await openApp(page, '邮件')
  await page.getByRole('button', { name: /HX217 订单取消成功/ }).click()
  await page.screenshot({ path: 'docs/images/stage2-mail.png', fullPage: true })
  await closeApp(page, '邮件')
  await openApp(page, '照片')
  await page.getByRole('button', { name: /IMG_1117_发给唐遥/ }).click()
  await page.getByRole('button', { name: '查看元数据' }).click()
  await expect(page.getByText('2031-08-03 18:46')).toBeVisible()
  await page.screenshot({ path: 'docs/images/stage2-photo-metadata.png', fullPage: true })
  expect(errors).toEqual([])
})

test('sub-1024, reduced-motion and safe mode keep the main investigation path usable', async ({ page }) => {
  const errors = watchErrors(page)
  const failedResources: string[] = []
  page.on('response', (response) => { if (response.status() >= 400) failedResources.push(`${response.status()} ${response.url()}`) })
  await page.setViewportSize({ width: 900, height: 700 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: '查看案件简介' }).click()
  await page.getByRole('button', { name: '开始调查' }).click()
  await page.getByRole('button', { name: '跳过启动' }).click()
  await page.getByRole('button', { name: '进入安全模式' }).click()
  await page.getByRole('button', { name: '跳过介绍' }).click()
  const desktop = page.getByTestId('desktop')
  await expect(desktop).toBeVisible()
  await expect(page.getByText('当前宽度会限制多窗口操作')).toBeVisible()
  await expect(desktop).not.toHaveClass(/anomalies/)
  await openApp(page, '邮件')
  const box = await page.getByRole('dialog', { name: '邮件' }).boundingBox()
  expect(box?.x).toBeGreaterThanOrEqual(0)
  expect(box?.y).toBeGreaterThanOrEqual(0)
  expect((box?.x ?? 0) + (box?.width ?? 0)).toBeLessThanOrEqual(900)
  expect((box?.y ?? 0) + (box?.height ?? 0)).toBeLessThanOrEqual(700)
  await page.keyboard.press('Escape')
  await page.getByRole('menuitem', { name: /保存并返回档案馆/ }).click()
  await expect(page.getByRole('heading', { name: /遗失的电脑/ })).toBeVisible()
  expect(errors).toEqual([])
  expect(failedResources).toEqual([])
})
