import { useState } from 'react'
import { caseDefinition } from '../../cases/case-001/case'
import { useGameStore } from '../../store/gameStore'
import { AppStatusBar, AppToolbar, PaneHeader } from './AppChrome'

export function CalendarApp() {
  const [mode, setMode] = useState<'month' | 'list'>('month'); const [selected, setSelected] = useState(caseDefinition.calendar[0]!); const investigate = useGameStore((state) => state.investigate)
  const select = (event: typeof selected) => { setSelected(event); investigate({ type: 'OPEN_ITEM', itemId: event.id }) }
  return <div className="application calendar-application"><AppToolbar><button>今天</button><button aria-label="上个月">←</button><strong>2031 年 11 月</strong><button aria-label="下个月">→</button><span className="path-field" /><button data-active={mode === 'month'} onClick={() => setMode('month')}>月</button><button data-active={mode === 'list'} onClick={() => setMode('list')}>列表</button></AppToolbar><div className="calendar-layout"><section className="calendar-main">{mode === 'month' ? <><div className="weekday-row">{['一', '二', '三', '四', '五', '六', '日'].map((day) => <span key={day}>周{day}</span>)}</div><div className="month-grid">{Array.from({ length: 35 }, (_, index) => { const day = index - 4; const events = caseDefinition.calendar.filter((event) => Number(event.date.slice(-2)) === day); return <div key={index} data-outside={day < 1 || day > 30}><time>{day > 0 && day <= 30 ? day : ''}</time>{events.map((event) => <button key={event.id} onClick={() => select(event)}>{event.title}</button>)}</div> })}</div></> : <div className="event-list">{caseDefinition.calendar.map((event) => <button key={event.id} onClick={() => select(event)}><time>{event.date}</time><span><strong>{event.title}</strong><small>{event.note}</small></span></button>)}</div>}</section><aside className="record-detail"><PaneHeader title="事件详情" /><h3>{selected.title}</h3><dl><dt>日期</dt><dd>{selected.date}</dd><dt>备注</dt><dd>{selected.note}</dd><dt>日历</dt><dd>ZHOU_YU / 个人</dd><dt>状态</dt><dd>未完成</dd></dl></aside></div><AppStatusBar><span>2031 年 11 月 · {caseDefinition.calendar.length} 个事件</span><span>本地日历快照</span></AppStatusBar></div>
}
