import { useState } from 'react'
import { useActiveCaseDefinition } from '../../cases/useActiveCase'

export function AudioWorkbenchApp() {
  const definition = useActiveCaseDefinition(); const [selected, setSelected] = useState(definition.audioTracks[0])
  return <div className="extended-app audio-runtime"><aside>{definition.audioTracks.map((track) => <button key={track.id} className={selected?.id === track.id ? 'selected' : ''} onClick={() => setSelected(track)}><strong>{track.title}</strong><small>{track.id}</small></button>)}</aside><section><header><span>AUDIO WORKBENCH</span><h2>{selected?.title ?? '没有音轨'}</h2></header><div className="audio-wave" aria-label="音频波形示意">{Array.from({ length: 48 }, (_item, index) => <i key={index} style={{ height: `${12 + ((index * 17) % 38)}px` }} />)}</div><h3>文字转写</h3><p>{selected?.transcript || '没有转写内容。'}</p></section></div>
}
export function BroadcastConsoleApp() { const definition = useActiveCaseDefinition(); return <div className="extended-app broadcast-runtime"><header><span>BROADCAST CONTROL</span><strong>节目事件线路</strong><b>LOCAL</b></header><div>{definition.broadcastEvents.map((event) => <article key={event.id}><time>{event.time}</time><div><strong>{event.title}</strong><p>{event.detail}</p></div></article>)}</div></div> }
export function DataDeskApp() { const definition = useActiveCaseDefinition(); const table = definition.dataTables[0]; return <div className="extended-app data-runtime"><header><span>DATA DESK</span><h2>{table?.title ?? '没有数据表'}</h2></header>{table && <table><thead><tr>{table.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{table.rows.map((row, index) => <tr key={index}>{row.map((value, cell) => <td key={cell}>{value}</td>)}</tr>)}</tbody></table>}</div> }
export function TerminalApp() { const definition = useActiveCaseDefinition(); const [selected, setSelected] = useState<string | null>(null); const entry = definition.terminalEntries.find((item) => item.id === selected); return <div className="extended-app terminal-runtime"><header>ARCHIVE/OS SAFE TERMINAL</header><div className="terminal-output">{entry ? <><span>$ {entry.command}</span><pre>{entry.output}</pre></> : <p>选择一个允许的命令。终端不会执行系统Shell。</p>}</div><footer>{definition.terminalEntries.filter((item) => item.enabled).map((item) => <button key={item.id} onClick={() => setSelected(item.id)}>{item.command}</button>)}</footer></div> }
export function VersionDiffApp() { const definition = useActiveCaseDefinition(); const [selected, setSelected] = useState(definition.versionDiffs[0]); return <div className="extended-app diff-runtime"><aside>{definition.versionDiffs.map((diff) => <button key={diff.id} onClick={() => setSelected(diff)}>{diff.title}</button>)}</aside><section><header>{selected?.title}</header><div><pre>{selected?.before}</pre><pre>{selected?.after}</pre></div></section></div> }
export function SitemapApp() { const definition = useActiveCaseDefinition(); const [selected, setSelected] = useState(definition.sitemap[0]); return <div className="extended-app sitemap-runtime"><header><span>SITE MAP</span><h2>地点关系</h2></header><div>{definition.sitemap.map((node, index) => <button key={node.id} style={{ marginLeft: node.parentId ? 80 : index * 20 }} onClick={() => setSelected(node)}><i />{node.label}</button>)}</div><aside><strong>{selected?.label}</strong><p>{selected?.detail}</p></aside></div> }
