import { useMemo, useState } from 'react'
import { caseDefinition } from '../../cases/case-001/case'
import type { VirtualFile } from '../../cases/types'
import { verifyItemPassword } from '../../engine/clueEngine'
import { useGameStore } from '../../store/gameStore'
import { AppStatusBar, AppToolbar, PaneHeader } from './AppChrome'

function FilePreview({ file }: { file: VirtualFile }) {
  const { investigate, unlockedItemIds, unlockMirror, openIdentityDraft } = useGameStore()
  const [password, setPassword] = useState(''); const [error, setError] = useState(false); const [transcript, setTranscript] = useState(false)
  if (file.id !== 'mirror.lock' && file.locked && !unlockedItemIds.includes(file.id)) return <div className="empty-state"><b>档案受 mirror.lock 保护</b><p>先在“不要打开”中解锁主档案。</p></div>
  if (file.id === 'mirror.lock' && !unlockedItemIds.includes('identity-draft')) return <form className="password-panel" onSubmit={(event) => { event.preventDefault(); if (verifyItemPassword(caseDefinition, file.id, password)) { unlockMirror(); setError(false) } else setError(true) }}><span>ENCRYPTED ARCHIVE</span><h3>输入四位访问密码</h3><input aria-label="mirror.lock 密码" inputMode="numeric" maxLength={4} value={password} onChange={(event) => setPassword(event.target.value.replace(/\D/g, ''))} /><button className="primary-button">解锁</button>{error && <p className="error-text">密码不正确。提示散落在日历里。</p>}</form>
  return <article className="document-view"><p className="document-meta">{file.name} · 本地档案</p><pre>{file.content}</pre>{file.id === 'recording' && <div className="recording-player"><div className="waveform">{Array.from({ length: 26 }, (_, index) => <i key={index} style={{ height: `${22 + (index * 19) % 50}%` }} />)}</div><button onClick={() => { setTranscript(true); investigate({ type: 'VIEW_TRANSCRIPT', itemId: 'recording' }) }}>辅助转写</button>{transcript && <p className="transcript">23:16，背景中出现本公寓电梯特有的双声提示音。</p>}</div>}{file.id === 'identity-draft' && <button className="secondary-button" onClick={openIdentityDraft}>检查身份草稿痕迹</button>}</article>
}

export function FilesApp() {
  const [folder, setFolder] = useState('旅行计划'); const [query, setQuery] = useState(''); const [descending, setDescending] = useState(false); const [selected, setSelected] = useState<VirtualFile | null>(null); const [properties, setProperties] = useState(false); const [rowMenu, setRowMenu] = useState(false)
  const investigate = useGameStore((state) => state.investigate); const openIdentityDraft = useGameStore((state) => state.openIdentityDraft)
  const visible = useMemo(() => caseDefinition.files.filter((file) => file.folder === folder && file.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (descending ? -1 : 1) * a.name.localeCompare(b.name)), [folder, query, descending])
  const selectFile = (file: VirtualFile) => { setSelected(file); setProperties(false); if (file.clueAction) investigate({ type: file.clueAction, itemId: file.id }); if (file.id === 'identity-draft') openIdentityDraft() }
  return <div className="application file-manager"><AppToolbar><button aria-label="后退">←</button><button aria-label="前进">→</button><span className="path-field">本机 / 用户 / ZHOU_YU / {folder}</span><input aria-label="搜索文件" placeholder="搜索当前文件夹" value={query} onChange={(event) => setQuery(event.target.value)} /><button onClick={() => setDescending(!descending)}>名称 {descending ? '↓' : '↑'}</button><button onClick={() => setProperties(!properties)}>属性</button></AppToolbar><div className="file-layout">
    <nav className="tree-pane" aria-label="文件夹"><PaneHeader title="快速访问" />{caseDefinition.folders.map((item) => <button key={item.id} data-active={folder === item.name} onClick={() => { setFolder(item.name); setSelected(null) }}><span aria-hidden="true">▾</span>{item.name}<small>{caseDefinition.files.filter((file) => file.folder === item.name).length}</small></button>)}</nav>
    <section className="file-table"><div className="data-head"><span>名称</span><span>类型</span><span>修改时间</span><span>大小</span></div>{visible.map((file, index) => <button key={file.id} data-selected={selected?.id === file.id} onClick={() => selectFile(file)} onDoubleClick={() => selectFile(file)} onContextMenu={(event) => { event.preventDefault(); setSelected(file); setRowMenu(true) }}><span><i className="file-symbol" aria-hidden="true">{file.locked ? '◇' : '□'}</i>{file.name}</span><span>{file.locked ? '受保护档案' : file.name.split('.').at(-1)?.toUpperCase()}</span><span>2031.11.{String(12 + index).padStart(2, '0')} 23:{String(index * 3).padStart(2, '0')}</span><span>{4 + index * 3} KB</span></button>)}{rowMenu && <div className="row-context" role="menu"><button onClick={() => { if (selected) selectFile(selected); setRowMenu(false) }}>打开</button><button onClick={() => { setProperties(true); setRowMenu(false) }}>查看属性</button></div>}</section>
    <section className="file-preview"><PaneHeader title={properties ? '属性' : '预览'} meta={selected?.name} />{selected ? properties ? <dl className="property-list"><dt>文件名</dt><dd>{selected.name}</dd><dt>原始路径</dt><dd>ZHOU_YU/{selected.folder}</dd><dt>档案 ID</dt><dd>{selected.id}</dd><dt>保护状态</dt><dd>{selected.locked ? '受保护' : '普通本地文件'}</dd></dl> : <FilePreview file={selected} /> : <div className="empty-state">选择一个项目以查看内容</div>}</section>
  </div><AppStatusBar><span>{visible.length} 个项目</span><span>{selected ? `已选择 1 个 · ${selected.name}` : '未选择项目'}</span><span>本地只读档案</span></AppStatusBar></div>
}
