import { useState } from 'react'
import { caseDefinition } from '../../cases/case-001/case'
import { useGameStore } from '../../store/gameStore'
import { AppStatusBar, AppToolbar, PaneHeader } from './AppChrome'

export function LogsApp() {
  const [user, setUser] = useState('全部'); const [type, setType] = useState('全部'); const [time, setTime] = useState('全部'); const [selected, setSelected] = useState(caseDefinition.logs[0]!); const investigate = useGameStore((state) => state.investigate)
  const logs = caseDefinition.logs.filter((log) => (user === '全部' || log.user === user) && (type === '全部' || log.eventType === type) && (time === '全部' || log.time.startsWith(time)))
  return <div className="application logs-application"><AppToolbar><select aria-label="时间筛选" value={time} onChange={(event) => setTime(event.target.value)}>{['全部', '2031-11-17', '2031-10-08'].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="用户筛选" value={user} onChange={(event) => setUser(event.target.value)}>{['全部', 'ZHOU_YU', 'LINRAN', 'SYSTEM'].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="事件类型筛选" value={type} onChange={(event) => setType(event.target.value)}>{['全部', '登录', '账户', '文件', '异常'].map((item) => <option key={item}>{item}</option>)}</select><span className="path-field">SYSTEM / EVENT JOURNAL</span><button>导出 CSV</button></AppToolbar><div className="logs-layout"><section className="log-data-table"><div className="data-head"><span>时间</span><span>用户</span><span>类型</span><span>事件</span></div>{logs.map((log) => <button key={log.id} data-selected={selected.id === log.id} onClick={() => { setSelected(log); investigate({ type: 'VIEW_LOG', itemId: log.id }) }}><time>{log.time}</time><b>{log.user}</b><span>{log.eventType}</span><strong>{log.detail}</strong></button>)}</section><aside className="record-detail"><PaneHeader title="事件详情" /><dl><dt>事件 ID</dt><dd>{selected.id}</dd><dt>时间戳</dt><dd>{selected.time}</dd><dt>用户</dt><dd>{selected.user}</dd><dt>事件类型</dt><dd>{selected.eventType}</dd><dt>详情</dt><dd>{selected.detail}</dd><dt>来源</dt><dd>ARCHIVE/OS 本地事件日志</dd></dl></aside></div><AppStatusBar><span>显示 {logs.length} / {caseDefinition.logs.length} 条</span><span>完整性：已验证</span></AppStatusBar></div>
}
