import { useState } from 'react'
import { caseDefinition } from '../../cases/case-001/case'
import { useGameStore } from '../../store/gameStore'
import { AppStatusBar, AppToolbar, PaneHeader } from './AppChrome'

export function PhotosApp() {
  const [index, setIndex] = useState(0); const [metadata, setMetadata] = useState(false); const [rotation, setRotation] = useState(0); const [zoom, setZoom] = useState(1)
  const photo = caseDefinition.photos[index]!; const investigate = useGameStore((state) => state.investigate); const togglePinned = useGameStore((state) => state.togglePinned); const discovered = useGameStore((state) => state.discoveredClueIds); const pinned = useGameStore((state) => state.pinnedClueIds)
  return <div className="application photos-app"><AppToolbar><button onClick={() => setRotation((value) => value - 90)}>向左旋转</button><button onClick={() => setRotation((value) => value + 90)}>向右旋转</button><button onClick={() => setZoom(Math.max(.6, zoom - .15))}>缩小</button><button onClick={() => setZoom(Math.min(2, zoom + .15))}>放大</button><span className="path-field">照片 / 2031 / 档案恢复</span><button className="primary-button" onClick={() => { setMetadata(true); investigate({ type: 'VIEW_METADATA', itemId: photo.id }) }}>查看元数据</button></AppToolbar><div className="photo-layout"><nav className="photo-library" aria-label="照片库"><PaneHeader title="2031 年 11 月" meta="2 张" />{caseDefinition.photos.map((item, itemIndex) => <button key={item.id} data-selected={index === itemIndex} onClick={() => { setIndex(itemIndex); setMetadata(false) }}><img src={item.image} alt="机场照片缩略图" /><span>{item.title}<small>{item.metadata.exportedAt.slice(0, 10)}</small></span></button>)}</nav><section className="photo-viewer"><img src={photo.image} alt="虚构海津机场候机区" style={{ transform: `rotate(${rotation}deg) scale(${zoom})` }} /><div className="viewer-index">{index + 1} / {caseDefinition.photos.length}</div></section><aside className="photo-info"><PaneHeader title="信息" meta={photo.title} /><dl><dt>文件名</dt><dd>{photo.title}</dd><dt>文件格式</dt><dd>SVG / 本地恢复图像</dd><dt>档案编号</dt><dd>{photo.id}</dd>{metadata && <><dt>原始拍摄</dt><dd>{photo.metadata.capturedAt}</dd><dt>导出时间</dt><dd>{photo.metadata.exportedAt}</dd><dt>设备</dt><dd>{photo.metadata.camera}</dd></>}</dl><button disabled={photo.id !== 'photo-sent' || !discovered.includes('C03')} onClick={() => togglePinned('C03')}>{pinned.includes('C03') ? '已加入证据板' : '加入证据板'}</button></aside></div><AppStatusBar><span>{photo.title}</span><span>旋转 {rotation}° · 缩放 {Math.round(zoom * 100)}%</span></AppStatusBar></div>
}
