import { useState } from 'react'
import { caseDefinition } from '../../cases/case-001/case'
import { useGameStore } from '../../store/gameStore'
import { AppStatusBar, AppToolbar, PaneHeader } from './AppChrome'

export function RecycleApp() {
  const unlocked = useGameStore((state) => state.unlockedItemIds); const investigate = useGameStore((state) => state.investigate); const [selected, setSelected] = useState<string | null>(null); const [restored, setRestored] = useState<string[]>([])
  const files = caseDefinition.files.filter((file) => file.folder === '回收站' && (!file.locked || unlocked.includes(file.id)) && !restored.includes(file.id)); const active = files.find((file) => file.id === selected)
  return <div className="application recycle-app"><AppToolbar><button disabled={!active} onClick={() => active && setRestored((items) => [...items, active.id])}>恢复所选</button><button disabled>清空回收站</button><span className="path-field">本机 / 回收站</span><span>{files.length} 个保留项目</span></AppToolbar><div className="recycle-layout"><section className="recycle-table"><div className="data-head"><span>名称</span><span>原始路径</span><span>删除时间</span><span>版本</span><span>状态</span></div>{files.map((file, index) => <button key={file.id} data-selected={selected === file.id} onClick={() => { setSelected(file.id); if (file.id === 'farewell-v3') investigate({ type: 'COMPARE_ITEMS', itemId: file.id }) }}><strong>{file.name}</strong><span>ZHOU_YU/日记</span><time>2031.11.17 23:{String(7 + index).padStart(2, '0')}</time><span>{file.name.match(/v\d/)?.[0] ?? '—'}</span><span>{file.locked ? '保护' : '可恢复'}</span></button>)}{files.length === 0 && <div className="empty-state"><b>回收站为空</b><p>已恢复的项目不会从案件存档中删除。</p></div>}</section><aside className="record-detail"><PaneHeader title="文件预览" meta={active?.name} />{active ? <><p>{active.content}</p><dl><dt>原始路径</dt><dd>用户/周屿/日记</dd><dt>删除方式</dt><dd>移动到回收站</dd><dt>保护状态</dt><dd>{active.locked ? '系统保护' : '普通'}</dd></dl><button className="secondary-button" onClick={() => { setRestored((items) => [...items, active.id]); setSelected(null) }}>恢复到原位置</button></> : <div className="empty-state">选择一个版本进行比较</div>}</aside></div><AppStatusBar><span>{files.length} 个项目</span><span>{restored.length} 个已恢复</span><span>保护项目不可清空</span></AppStatusBar></div>
}
