import { useEffect, useMemo, useState } from 'react'
import type { EvidenceRelation } from '../../cases/types'
import { caseDefinition } from '../../cases/case-001/case'
import { useGameStore } from '../../store/gameStore'
import { EvidenceCard } from './EvidenceCard'
import { filterEvidenceClues } from './evidenceFilters'

export function EvidenceBoardApp() {
  const { discoveredClueIds, pinnedClueIds, evidenceRelations, togglePinned, addRelation, removeRelation, setCardPosition } = useGameStore()
  const [filters, setFilters] = useState({ source: '', person: '', time: '', place: '' }); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [type, setType] = useState<EvidenceRelation['type']>('相互矛盾'); const [deducing, setDeducing] = useState(false)
  const positions = useGameStore((state) => state.evidenceCardPositions)
  const clues = useMemo(() => filterEvidenceClues(caseDefinition.clues.filter((clue) => discoveredClueIds.includes(clue.id)), filters), [discoveredClueIds, filters])
  return <div className="evidence-app" data-testid="evidence-board"><header className="evidence-header"><div><p>CASE 001 / EVIDENCE MATRIX</p><h3>证据板</h3></div><div className="evidence-progress"><span>已发现</span><strong>{discoveredClueIds.length} / 12</strong></div><button className="primary-button" disabled={discoveredClueIds.length < 6} onClick={() => setDeducing(true)}>{discoveredClueIds.length < 6 ? `还需 ${6 - discoveredClueIds.length} 条线索` : '打开最终推理'}</button></header>
    <div className="evidence-filters"><select aria-label="来源筛选" value={filters.source} onChange={(event) => setFilters((value) => ({ ...value, source: event.target.value }))}><option value="">全部来源</option>{['mail', 'messages', 'photos', 'browser', 'calendar', 'recycle', 'logs', 'files'].map((item) => <option key={item}>{item}</option>)}</select><input aria-label="人物筛选" placeholder="人物" value={filters.person} onChange={(event) => setFilters((value) => ({ ...value, person: event.target.value }))}/><input aria-label="时间筛选" placeholder="时间" value={filters.time} onChange={(event) => setFilters((value) => ({ ...value, time: event.target.value }))}/><input aria-label="地点筛选" placeholder="地点" value={filters.place} onChange={(event) => setFilters((value) => ({ ...value, place: event.target.value }))}/></div>
    <div className="evidence-workspace"><svg className="relation-lines" aria-hidden="true">{evidenceRelations.map((relation, index) => <g key={relation.id}><line x1={130 + index * 35} y1="80" x2={300 + index * 20} y2="250" /><text x={190 + index * 30} y="160">{relation.type}</text></g>)}</svg>{clues.map((clue, index) => <EvidenceCard key={clue.id} clue={clue} pinned={pinnedClueIds.includes(clue.id)} position={positions[clue.id] ?? { x: 24 + (index % 3) * 250, y: 26 + Math.floor(index / 3) * 175 }} onToggle={() => togglePinned(clue.id)} onMove={(x, y) => setCardPosition(clue.id, x, y)} />)}</div>
    <section className="relation-builder"><h4>建立证据关系</h4><select aria-label="关系起点" value={from} onChange={(event) => setFrom(event.target.value)}><option value="">选择证据 A</option>{discoveredClueIds.map((id) => <option key={id}>{id}</option>)}</select><select aria-label="关系类型" value={type} onChange={(event) => setType(event.target.value as EvidenceRelation['type'])}>{['相互矛盾', '相互支持', '时间先后', '同一人物'].map((item) => <option key={item}>{item}</option>)}</select><select aria-label="关系终点" value={to} onChange={(event) => setTo(event.target.value)}><option value="">选择证据 B</option>{discoveredClueIds.map((id) => <option key={id}>{id}</option>)}</select><button disabled={!from || !to || from === to} onClick={() => { addRelation(from, to, type); setFrom(''); setTo('') }}>连接</button><ul>{evidenceRelations.map((relation) => <li key={relation.id}><span>{relation.from} — {relation.type} — {relation.to}</span><button aria-label={`删除关系 ${relation.from} ${relation.to}`} onClick={() => removeRelation(relation.id)}>删除</button></li>)}</ul></section>
    {deducing && <DeductionDialog onClose={() => setDeducing(false)} />}
  </div>
}

function DeductionDialog({ onClose }: { onClose: () => void }) {
  const { discoveredClueIds, pinnedClueIds, evidenceRelations, deductionResult, submit } = useGameStore()
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [note, setNote] = useState(''); const [result, setResult] = useState(deductionResult)
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose])
  const contradictionCount = evidenceRelations.filter((relation) => relation.type === '相互矛盾').length
  if (result) return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="推理结果"><article className="deduction-card result-card"><button className="modal-close" aria-label="关闭推理结果" onClick={onClose}>×</button><p className="eyebrow">ARCHIVE RECONSTRUCTION</p><div className="score-ring"><strong>{result.score}</strong><span>/100</span></div><h2>{result.level}</h2><div className="score-breakdown"><span>核心判断 {result.answerScore}/65</span><span>证据覆盖 {result.evidenceScore}/30</span><span>矛盾关系 {result.relationScore}/5</span></div><p>发现线索：{discoveredClueIds.length}/12 · 核心线索：{discoveredClueIds.filter((id) => caseDefinition.coreEvidenceIds.includes(id)).length}/{caseDefinition.coreEvidenceIds.length}</p><p>玩家选择：{pinnedClueIds.join('、') || '未选择'} · 忽略的关键线索：{caseDefinition.coreEvidenceIds.filter((id) => !pinnedClueIds.includes(id)).join('、') || '无'}</p>{result.note && <blockquote>{result.note}</blockquote>}<div className="ending"><p>正在核对系统日志……</p><p>检测到新的本地会话。</p><p>用户 LINRAN 登录成功。</p><strong>{caseDefinition.ending}</strong></div></article></div>
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="最终推理"><form className="deduction-card" onSubmit={(event) => { event.preventDefault(); const ordered = caseDefinition.questions.map((question) => answers[question.id] ?? ''); setResult(submit(ordered, note)) }}><button type="button" className="modal-close" aria-label="关闭最终推理" onClick={onClose}>×</button><p className="eyebrow">FINAL DEDUCTION</p><h2>重建最后一次登录</h2>{caseDefinition.questions.map((question, questionIndex) => <fieldset key={question.id}><legend><span>0{questionIndex + 1}</span>{question.prompt}</legend>{question.options.map((option) => <label key={option.id}><input required type="radio" name={question.id} value={option.id} checked={answers[question.id] === option.id} onChange={() => setAnswers((state) => ({ ...state, [question.id]: option.id }))} />{option.label}</label>)}</fieldset>)}<section className="deduction-evidence"><h3>你的关键证据</h3><p>{pinnedClueIds.length}/6：{pinnedClueIds.join('、') || '请先在证据板标记关键证据'}</p><p>矛盾关系：{contradictionCount} 组</p></section><label className="note-field">个人推理（只保存在本地）<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="primary-button" disabled={!pinnedClueIds.length || contradictionCount < 1}>提交推理</button></form></div>
}
