import { useEditorStore } from '../../store/editorStore'

function Shell({ code, title, note, action, children }: { code: string; title: string; note: string; action: React.ReactNode; children: React.ReactNode }) {
  return <section className="editor-document"><header><div><span>{code}</span><h1>{title}</h1><p>{note}</p></div>{action}</header>{children}</section>
}

export function PhotoEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="PHOTO CATALOG" title="照片" note="照片谜底应通过元数据查看动作触发；资源必须来自本地资源管理器。" action={<button onClick={() => updateDraft((draft) => { draft.photos.push({ id: `photo-${draft.photos.length + 1}`, title: '新照片', image: '', metadata: { capturedAt: '', exportedAt: '', camera: '' } }) }, 'photo-add')}>添加照片</button>}><div className="record-table"><div><b>标题</b><b>原始拍摄时间</b><b>导出时间</b><b>设备</b></div>{project.draft.photos.map((photo, index) => <div key={photo.id}><input aria-label={`照片 ${index + 1} 标题`} value={photo.title} onChange={(event) => updateDraft((draft) => { draft.photos[index]!.title = event.target.value }, `photo.${photo.id}.title`)} /><input aria-label={`照片 ${index + 1} 拍摄时间`} value={photo.metadata.capturedAt} onChange={(event) => updateDraft((draft) => { draft.photos[index]!.metadata.capturedAt = event.target.value }, `photo.${photo.id}.captured`)} /><input aria-label={`照片 ${index + 1} 导出时间`} value={photo.metadata.exportedAt} onChange={(event) => updateDraft((draft) => { draft.photos[index]!.metadata.exportedAt = event.target.value }, `photo.${photo.id}.exported`)} /><input aria-label={`照片 ${index + 1} 设备`} value={photo.metadata.camera} onChange={(event) => updateDraft((draft) => { draft.photos[index]!.metadata.camera = event.target.value }, `photo.${photo.id}.camera`)} /></div>)}</div></Shell>
}

export function BrowserEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="BROWSER HISTORY" title="浏览记录" note="页面标题和分类是虚构记录，不允许写入真实远程URL。" action={<button onClick={() => updateDraft((draft) => { draft.browserHistory.push({ id: `history-${draft.browserHistory.length + 1}`, time: '12:00', title: '新浏览记录', category: '普通' }) }, 'history-add')}>添加记录</button>}><div className="record-table three"><div><b>时间</b><b>页面标题</b><b>分类</b></div>{project.draft.browserHistory.map((entry, index) => <div key={entry.id}><input value={entry.time} aria-label={`浏览记录 ${index + 1} 时间`} onChange={(event) => updateDraft((draft) => { draft.browserHistory[index]!.time = event.target.value }, `browser.${entry.id}.time`)} /><input value={entry.title} aria-label={`浏览记录 ${index + 1} 标题`} onChange={(event) => updateDraft((draft) => { draft.browserHistory[index]!.title = event.target.value }, `browser.${entry.id}.title`)} /><input value={entry.category} aria-label={`浏览记录 ${index + 1} 分类`} onChange={(event) => updateDraft((draft) => { draft.browserHistory[index]!.category = event.target.value }, `browser.${entry.id}.category`)} /></div>)}</div></Shell>
}

export function CalendarEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="CALENDAR EVENTS" title="日历" note="在月历中呈现的事件，备注只在玩家打开详情后显示。" action={<button onClick={() => updateDraft((draft) => { draft.calendarEvents.push({ id: `calendar-${draft.calendarEvents.length + 1}`, date: '2032-01-01', title: '新日程', note: '' }) }, 'calendar-add')}>添加日程</button>}><div className="record-table three"><div><b>日期</b><b>标题</b><b>详情备注</b></div>{project.draft.calendarEvents.map((entry, index) => <div key={entry.id}><input type="date" value={entry.date} aria-label={`日历 ${index + 1} 日期`} onChange={(event) => updateDraft((draft) => { draft.calendarEvents[index]!.date = event.target.value }, `calendar.${entry.id}.date`)} /><input value={entry.title} aria-label={`日历 ${index + 1} 标题`} onChange={(event) => updateDraft((draft) => { draft.calendarEvents[index]!.title = event.target.value }, `calendar.${entry.id}.title`)} /><input value={entry.note} aria-label={`日历 ${index + 1} 备注`} onChange={(event) => updateDraft((draft) => { draft.calendarEvents[index]!.note = event.target.value }, `calendar.${entry.id}.note`)} /></div>)}</div></Shell>
}

export function LogEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="SYSTEM EVENT LOG" title="系统日志" note="日志详情触发线索时，玩家必须主动打开该行。" action={<button onClick={() => updateDraft((draft) => { draft.systemLogs.push({ id: `log-${draft.systemLogs.length + 1}`, time: '2032-01-01 12:00', user: 'SYSTEM', eventType: '信息', detail: '新日志记录' }) }, 'log-add')}>添加日志</button>}><div className="record-table four"><div><b>时间</b><b>用户</b><b>类型</b><b>详情</b></div>{project.draft.systemLogs.map((entry, index) => <div key={entry.id}><input value={entry.time} aria-label={`日志 ${index + 1} 时间`} onChange={(event) => updateDraft((draft) => { draft.systemLogs[index]!.time = event.target.value }, `log.${entry.id}.time`)} /><input value={entry.user} aria-label={`日志 ${index + 1} 用户`} onChange={(event) => updateDraft((draft) => { draft.systemLogs[index]!.user = event.target.value }, `log.${entry.id}.user`)} /><input value={entry.eventType} aria-label={`日志 ${index + 1} 类型`} onChange={(event) => updateDraft((draft) => { draft.systemLogs[index]!.eventType = event.target.value }, `log.${entry.id}.type`)} /><input value={entry.detail} aria-label={`日志 ${index + 1} 详情`} onChange={(event) => updateDraft((draft) => { draft.systemLogs[index]!.detail = event.target.value }, `log.${entry.id}.detail`)} /></div>)}</div></Shell>
}

export function AudioEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="AUDIO WORKBENCH" title="音频工作台" note="音频资源必须有文字转写；波形不作为唯一的信息表达方式。" action={<button onClick={() => updateDraft((draft) => { draft.audioTracks.push({ id: `audio-${draft.audioTracks.length + 1}`, title: '新音轨', assetId: '', transcript: '' }) }, 'audio-add')}>添加音轨</button>}><div className="record-table three"><div><b>名称</b><b>资源ID</b><b>文字转写</b></div>{project.draft.audioTracks.map((entry, index) => <div key={entry.id}><input value={entry.title} aria-label={`音轨 ${index + 1} 名称`} onChange={(event) => updateDraft((draft) => { draft.audioTracks[index]!.title = event.target.value }, `audio.${entry.id}.title`)} /><input value={entry.assetId} aria-label={`音轨 ${index + 1} 资源`} onChange={(event) => updateDraft((draft) => { draft.audioTracks[index]!.assetId = event.target.value }, `audio.${entry.id}.asset`)} /><input value={entry.transcript} aria-label={`音轨 ${index + 1} 转写`} onChange={(event) => updateDraft((draft) => { draft.audioTracks[index]!.transcript = event.target.value }, `audio.${entry.id}.transcript`)} /></div>)}</div></Shell>
}

export function BroadcastEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="BROADCAST CONSOLE" title="广播控制台" note="广播事件按时间顺序呈现，不执行自定义脚本。" action={<button onClick={() => updateDraft((draft) => { draft.broadcastEvents.push({ id: `broadcast-${draft.broadcastEvents.length + 1}`, time: '00:00', title: '新广播事件', detail: '' }) }, 'broadcast-add')}>添加事件</button>}><div className="record-table three"><div><b>时间</b><b>标题</b><b>详情</b></div>{project.draft.broadcastEvents.map((entry, index) => <div key={entry.id}><input value={entry.time} aria-label={`广播 ${index + 1} 时间`} onChange={(event) => updateDraft((draft) => { draft.broadcastEvents[index]!.time = event.target.value }, `broadcast.${entry.id}.time`)} /><input value={entry.title} aria-label={`广播 ${index + 1} 标题`} onChange={(event) => updateDraft((draft) => { draft.broadcastEvents[index]!.title = event.target.value }, `broadcast.${entry.id}.title`)} /><input value={entry.detail} aria-label={`广播 ${index + 1} 详情`} onChange={(event) => updateDraft((draft) => { draft.broadcastEvents[index]!.detail = event.target.value }, `broadcast.${entry.id}.detail`)} /></div>)}</div></Shell>
}

export function DataEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="DATA TABLES" title="数据台" note="表格只包含本地字符串数据，不支持公式或代码执行。" action={<button onClick={() => updateDraft((draft) => { draft.dataTables.push({ id: `data-${draft.dataTables.length + 1}`, title: '新数据表', columns: ['字段A', '字段B'], rows: [['', '']] }) }, 'data-add')}>添加数据表</button>}><div className="record-table three"><div><b>名称</b><b>列名（逗号分隔）</b><b>首行数据</b></div>{project.draft.dataTables.map((entry, index) => <div key={entry.id}><input value={entry.title} aria-label={`数据表 ${index + 1} 名称`} onChange={(event) => updateDraft((draft) => { draft.dataTables[index]!.title = event.target.value }, `data.${entry.id}.title`)} /><input value={entry.columns.join(',')} aria-label={`数据表 ${index + 1} 列`} onChange={(event) => updateDraft((draft) => { draft.dataTables[index]!.columns = event.target.value.split(',') }, `data.${entry.id}.columns`)} /><input value={entry.rows[0]?.join(',') ?? ''} aria-label={`数据表 ${index + 1} 首行`} onChange={(event) => updateDraft((draft) => { draft.dataTables[index]!.rows[0] = event.target.value.split(',') }, `data.${entry.id}.row`)} /></div>)}</div></Shell>
}

export function TerminalEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="SAFE TERMINAL COMMANDS" title="模拟终端" note="命令只匹配预先配置的文本输出，永远不会调用系统Shell。" action={<button onClick={() => updateDraft((draft) => { draft.terminalEntries.push({ id: `terminal-${draft.terminalEntries.length + 1}`, command: 'help', output: '可用命令', enabled: true }) }, 'terminal-add')}>添加白名单命令</button>}><div className="record-table three"><div><b>命令文本</b><b>固定输出</b><b>状态</b></div>{project.draft.terminalEntries.map((entry, index) => <div key={entry.id}><input value={entry.command} aria-label={`终端命令 ${index + 1}`} onChange={(event) => updateDraft((draft) => { draft.terminalEntries[index]!.command = event.target.value }, `terminal.${entry.id}.command`)} /><input value={entry.output} aria-label={`终端输出 ${index + 1}`} onChange={(event) => updateDraft((draft) => { draft.terminalEntries[index]!.output = event.target.value }, `terminal.${entry.id}.output`)} /><label className="check-field"><input type="checkbox" checked={entry.enabled} onChange={(event) => updateDraft((draft) => { draft.terminalEntries[index]!.enabled = event.target.checked }, `terminal.${entry.id}.enabled`)} />允许显示</label></div>)}</div></Shell>
}

export function VersionEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="VERSION DIFF" title="版本差异" note="并排编辑修改前与修改后的纯文本版本。" action={<button onClick={() => updateDraft((draft) => { draft.versionDiffs.push({ id: `version-${draft.versionDiffs.length + 1}`, title: '新版本差异', before: '', after: '' }) }, 'version-add')}>添加差异</button>}><div className="record-table three"><div><b>标题</b><b>修改前</b><b>修改后</b></div>{project.draft.versionDiffs.map((entry, index) => <div key={entry.id}><input value={entry.title} aria-label={`版本 ${index + 1} 标题`} onChange={(event) => updateDraft((draft) => { draft.versionDiffs[index]!.title = event.target.value }, `version.${entry.id}.title`)} /><input value={entry.before} aria-label={`版本 ${index + 1} 修改前`} onChange={(event) => updateDraft((draft) => { draft.versionDiffs[index]!.before = event.target.value }, `version.${entry.id}.before`)} /><input value={entry.after} aria-label={`版本 ${index + 1} 修改后`} onChange={(event) => updateDraft((draft) => { draft.versionDiffs[index]!.after = event.target.value }, `version.${entry.id}.after`)} /></div>)}</div></Shell>
}

export function SitemapEditor() {
  const { currentProject: project, updateDraft } = useEditorStore(); if (!project) return null
  return <Shell code="SITE MAP" title="站点地图" note="用父节点ID建立地点层级；依赖图同时提供文字列表。" action={<button onClick={() => updateDraft((draft) => { draft.sitemap.push({ id: `site-${draft.sitemap.length + 1}`, label: '新地点', detail: '' }) }, 'site-add')}>添加地点</button>}><div className="record-table three"><div><b>地点名称</b><b>父节点ID</b><b>说明</b></div>{project.draft.sitemap.map((entry, index) => <div key={entry.id}><input value={entry.label} aria-label={`地点 ${index + 1} 名称`} onChange={(event) => updateDraft((draft) => { draft.sitemap[index]!.label = event.target.value }, `site.${entry.id}.label`)} /><input value={entry.parentId ?? ''} aria-label={`地点 ${index + 1} 父节点`} onChange={(event) => updateDraft((draft) => { draft.sitemap[index]!.parentId = event.target.value || undefined }, `site.${entry.id}.parent`)} /><input value={entry.detail} aria-label={`地点 ${index + 1} 说明`} onChange={(event) => updateDraft((draft) => { draft.sitemap[index]!.detail = event.target.value }, `site.${entry.id}.detail`)} /></div>)}</div></Shell>
}
