import { useEditorStore } from '../../store/editorStore'

export function MetadataEditor({ compact = false }: { compact?: boolean }) {
  const project = useEditorStore((state) => state.currentProject)
  const updateDraft = useEditorStore((state) => state.updateDraft)
  if (!project) return null
  const manifest = project.draft.manifest
  const subject = project.draft.subject
  const setManifest = (key: keyof typeof manifest, value: string | number) => updateDraft((draft) => { Object.assign(draft.manifest, { [key]: value }) }, `manifest.${String(key)}`)
  if (compact) return <div className="overview-title-form"><label>案件标题<input id="field-manifest-title" value={manifest.title ?? ''} onChange={(event) => setManifest('title', event.target.value)} /></label><label>作者<input value={manifest.author ?? ''} onChange={(event) => setManifest('author', event.target.value)} /></label></div>
  return <section className="editor-document"><header><span>CASE METADATA</span><h1>基本信息</h1><p>这些字段会显示在档案馆案件卡片和发布包清单中。</p></header><div className="form-section"><h2>案件标识</h2><div className="editor-form"><label>caseId<input value={manifest.caseId ?? ''} pattern="[a-z0-9-]+" onChange={(event) => setManifest('caseId', event.target.value)} /><small>只能使用小写字母、数字和连字符</small></label><label>案件版本<input value={manifest.version ?? ''} onChange={(event) => setManifest('version', event.target.value)} /></label><label>案件标题<input id="field-manifest-title" value={manifest.title ?? ''} onChange={(event) => setManifest('title', event.target.value)} /></label><label>副标题<input value={manifest.subtitle ?? ''} onChange={(event) => setManifest('subtitle', event.target.value)} /></label><label>作者<input value={manifest.author ?? ''} onChange={(event) => setManifest('author', event.target.value)} /></label><label>语言<select value={manifest.language ?? 'zh-CN'} onChange={(event) => setManifest('language', event.target.value)}><option>zh-CN</option><option>en-US</option></select></label><label>难度<select value={manifest.difficulty ?? '入门'} onChange={(event) => setManifest('difficulty', event.target.value)}><option>入门</option><option>普通</option><option>困难</option></select></label><label>建议时长（分钟）<input type="number" min="1" value={manifest.estimatedMinutes ?? 15} onChange={(event) => setManifest('estimatedMinutes', Number(event.target.value))} /></label></div><label className="wide-field">案件简介<textarea value={manifest.summary ?? ''} onChange={(event) => setManifest('summary', event.target.value)} /></label></div><div className="form-section"><h2>电脑主人</h2><div className="editor-form"><label>主人名称<input value={subject.name ?? ''} onChange={(event) => updateDraft((draft) => { draft.subject.name = event.target.value }, 'subject.name')} /></label><label>年龄<input type="number" value={subject.age ?? ''} onChange={(event) => updateDraft((draft) => { draft.subject.age = Number(event.target.value) }, 'subject.age')} /></label><label>职业<input value={subject.occupation ?? ''} onChange={(event) => updateDraft((draft) => { draft.subject.occupation = event.target.value }, 'subject.occupation')} /></label><label>地点<input value={subject.location ?? ''} onChange={(event) => updateDraft((draft) => { draft.subject.location = event.target.value }, 'subject.location')} /></label><label>最后登录时间<input value={subject.lastLoginAt ?? ''} onChange={(event) => updateDraft((draft) => { draft.subject.lastLoginAt = event.target.value }, 'subject.lastLoginAt')} /></label><label>归档时间<input value={manifest.archivedAt ?? ''} onChange={(event) => setManifest('archivedAt', event.target.value)} /></label></div></div></section>
}

