import { useState } from 'react'
import { ConditionBuilder } from '../condition-builder/ConditionBuilder'
import { useEditorStore } from '../../store/editorStore'

export function ClueEditor() {
  const project = useEditorStore((state) => state.currentProject)
  const updateDraft = useEditorStore((state) => state.updateDraft)
  const [selectedId, setSelectedId] = useState(project?.draft.clues[0]?.id ?? null)
  if (!project) return null
  const selected = project.draft.clues.find((clue) => clue.id === selectedId)
  const targets = [...project.draft.files.map((item) => ({ id: item.id, label: `文件 · ${item.name}` })), ...project.draft.emails.map((item) => ({ id: item.id, label: `邮件 · ${item.subject}` })), ...project.draft.chats.flatMap((thread) => thread.messages.map((item) => ({ id: item.id, label: `消息 · ${thread.title}` }))), ...project.draft.calendarEvents.map((item) => ({ id: item.id, label: `日历 · ${item.title}` })), ...project.draft.systemLogs.map((item) => ({ id: item.id, label: `日志 · ${item.eventType}` }))]
  return <section className="editor-document"><header><div><span>CLUE LOGIC</span><h1>线索与条件</h1><p>用事件、AND、OR和前置线索组成可读的声明式发现条件。</p></div><button className="primary-button" onClick={() => updateDraft((draft) => { const id = `clue-new-${draft.clues.length + 1}`; draft.clues.push({ id, title: '新线索', summary: '', explanation: '', source: 'files', discovery: { type: 'OPEN_ITEM', itemId: targets[0]?.id ?? '' }, condition: { type: 'event', eventType: 'OPEN_ITEM', targetId: targets[0]?.id ?? '' }, people: [], times: [], places: [], isCore: false, isRedHerring: false }); setSelectedId(id) }, 'clue-add')}>新建线索</button></header><div className="clue-author"><aside>{project.draft.clues.map((clue, index) => <button key={clue.id} className={clue.id === selectedId ? 'selected' : ''} onClick={() => setSelectedId(clue.id)}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{clue.title}</strong><small>{clue.id}</small></div></button>)}</aside>{selected ? <div className="clue-editor-main"><div className="editor-form"><label>稳定ID<input value={selected.id} readOnly /></label><label>线索标题<input value={selected.title} onChange={(event) => updateDraft((draft) => { draft.clues.find((item) => item.id === selected.id)!.title = event.target.value }, `clue.${selected.id}.title`)} /></label><label>来源应用<select value={selected.source} onChange={(event) => updateDraft((draft) => { draft.clues.find((item) => item.id === selected.id)!.source = event.target.value as typeof selected.source }, `clue.${selected.id}.source`)}>{project.draft.applications.filter((app) => app.enabled).map((app) => <option key={app.id} value={app.id}>{app.title}</option>)}</select></label><label className="check-field"><input type="checkbox" checked={selected.isCore} onChange={(event) => updateDraft((draft) => { draft.clues.find((item) => item.id === selected.id)!.isCore = event.target.checked }, `clue.${selected.id}.core`)} />关键证据</label></div><label className="wide-field">玩家摘要<textarea value={selected.summary} onChange={(event) => updateDraft((draft) => { draft.clues.find((item) => item.id === selected.id)!.summary = event.target.value }, `clue.${selected.id}.summary`)} /></label><ConditionBuilder condition={selected.condition} targets={targets} onChange={(condition) => updateDraft((draft) => { const clue = draft.clues.find((item) => item.id === selected.id); if (clue) { clue.condition = condition; if (condition.type === 'event') clue.discovery = { type: condition.eventType as typeof clue.discovery.type, itemId: condition.targetId } } }, `clue.${selected.id}.condition`)} /></div> : <div className="editor-empty">选择或创建线索。</div>}</div></section>
}
