import type { CaseCondition, GameEventType } from '../../../cases/types'

const eventTypes: { value: GameEventType; label: string }[] = [{ value: 'OPEN_ITEM', label: '打开内容' }, { value: 'VIEW_METADATA', label: '查看元数据' }, { value: 'VIEW_LOG', label: '查看日志详情' }, { value: 'UNLOCK_ITEM', label: '解锁内容' }, { value: 'RESTORE_ITEM', label: '恢复文件' }, { value: 'VIEW_TRANSCRIPT', label: '查看转写' }]

function ConditionNode({ condition, onChange, onRemove, targets, depth = 1 }: { condition: CaseCondition; onChange: (condition: CaseCondition) => void; onRemove?: () => void; targets: { id: string; label: string }[]; depth?: number }) {
  const type = condition.type
  return <div className={`condition-node type-${type}`}><div className="condition-node-head"><select aria-label={`条件类型 第${depth}层`} value={type} onChange={(event) => { const next = event.target.value; if (next === 'all' || next === 'any') onChange({ type: next, conditions: [{ type: 'event', eventType: 'OPEN_ITEM', targetId: targets[0]?.id ?? '' }] }); else if (next === 'clue-count') onChange({ type: 'clue-count', count: 1 }); else onChange({ type: 'event', eventType: 'OPEN_ITEM', targetId: targets[0]?.id ?? '' }) }}><option value="event">事件发生</option><option value="all">全部满足（AND）</option><option value="any">任一满足（OR）</option><option value="clue-count">线索数量</option></select>{onRemove && <button aria-label="删除条件" onClick={onRemove}>×</button>}</div>{type === 'event' && <div className="condition-fields"><select aria-label="事件类型" value={condition.eventType} onChange={(event) => onChange({ ...condition, eventType: event.target.value as GameEventType })}>{eventTypes.map((event) => <option key={event.value} value={event.value}>{event.label}</option>)}</select><select aria-label="事件目标" value={condition.targetId} onChange={(event) => onChange({ ...condition, targetId: event.target.value })}><option value="">选择目标</option>{targets.map((target) => <option key={target.id} value={target.id}>{target.label}</option>)}</select></div>}{type === 'clue-count' && <label>至少发现<input type="number" min="1" value={condition.count} onChange={(event) => onChange({ ...condition, count: Number(event.target.value) })} />条线索</label>}{(type === 'all' || type === 'any') && <div className="condition-children">{condition.conditions.map((child, index) => <ConditionNode key={index} condition={child} targets={targets} depth={depth + 1} onChange={(next) => onChange({ ...condition, conditions: condition.conditions.map((item, childIndex) => childIndex === index ? next : item) })} onRemove={() => onChange({ ...condition, conditions: condition.conditions.filter((_item, childIndex) => childIndex !== index) })} />)}<button disabled={depth >= 5} onClick={() => onChange({ ...condition, conditions: [...condition.conditions, { type: 'event', eventType: 'OPEN_ITEM', targetId: targets[0]?.id ?? '' }] })}>添加子条件</button></div>}</div>
}

export function ConditionBuilder({ condition, onChange, targets }: { condition: CaseCondition; onChange: (condition: CaseCondition) => void; targets: { id: string; label: string }[] }) {
  return <section className="condition-builder"><header><div><span>WHEN</span><h3>发现条件</h3></div><button onClick={() => onChange({ type: 'all', conditions: [condition, { type: 'event', eventType: 'OPEN_ITEM', targetId: targets[0]?.id ?? '' }] })}>添加AND组</button></header><ConditionNode condition={condition} onChange={onChange} targets={targets} /><details><summary>查看声明式数据</summary><pre>{JSON.stringify(condition, null, 2)}</pre></details></section>
}

